### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by thiendangit** [thiendangit/MTStoreReactJS#4]
- [x] - Typescript là gì ? 
- [x] - Cách khai báo (interface & type) ( viết 4 ví dụ )
- [x] - Cái type trong typescript (string, number, boolean, any, ...) (liệt kê tất cả)
- [x] - Tìm hiểu cách viết function với typescript
-  tính tổng 2 số và trả về number 
- tìm tất cả số lẻ trong mảng [102,103,111,211,222,555,542,112] và trả về mảng kết quả kiểu number
- [x] - Tìm hiểu cách khai báo component với typescript ( chụp hình 1 component )

**Comment by thaominh97** [comment]
import React from "react";

interface Animals {
    feet: number;
    namePet: string;
    a: number;
    b: number;
}

let arr = [102, 103, 111, 211, 222, 555, 542, 112], newArr: number[] = [];
for (let i = 0; i < arr.length; i++) {
    if ( arr[i] % 2 === 0){
        newArr.push(arr[i]);
        console.log(newArr);
    }
}
const Pet = (props: Animals) => {
    return (
        <>
            <p>My Pet is {props.namePet}. It has {props.feet} feet and {props.a + props.b};<br />
                mảng chẵn: {newArr.join(',')}</p>

        </>
    );
};
export default Pet;

**Comment by thaominh97** [comment]
* TypeScript là một ngôn ngữ mã nguồn mở của JavaScript; dùng để thiết kế và xây dựng các dự án ứng dụng quy mô lớn mang tính chất phức tạp.
>Để khai báo một component kết hợp TypeScript trong React, và thêm: React.FC sau tên component.

>Các kiểu dữ liệu phổ biến: 
-Any – có thể có giá trị là một string, number hoặc bất kỳ kiểu nào.
-String – chuỗi.
- Number – Tất cả giá trị số trong hàm đều được biểu diễn bởi kiểu number, không có định nghĩa riêng cho số nguyên (interger), số thực (float) cũng như các kiểu khác.
-Boolean – true hoặc false.
- Arrays – Mảng.
- Void – sử dụng khi hàm không trả lại bất kỳ giá trị nào.

> Link TypeScript Playground:
https://www.typescriptlang.org/play?#code/C4TwDgpgBAYhCGwCuAnaBeKBvAUFfUAxgBYCWKYAXFAM7AqkB2A5jgL445PAQoBm8QtACCjUgFt4AGxrY8BPhAjBqjJOIBGvANzz8jeOIgAFZdToMWugkTIVqcRKggBtAOQlyYNwF1dbXRxCAHtGOigAFWDgaShMAAp4VXUtFAAaKA1kzV4ASjiAPih4KABqTN0QsOCpCAA6KWDmeKiYqXiAZgyAVlzcwNrgYpQUOKgXAEYABgAmDOmuqAnljJmVqBnNnu7unoAWOaWJmb8g0PDhEYAlCBokKSGE-PQi3BtBqEYIAHdLlGzUi4fGMgdYFMFRvEPqQxlNtFAYQAeYYoBoQFjAYjw0ilUr5N42AikPhQRIjFykYEAUg2cXQmCm+L0hJsX1+IzqYCQNGIZJQFJ8-WZLPwVRoNXqjWabL+QpFUA4Ng4HD+NzuD3iQrFQwAQuQACbUUQSaSyTBYRRmKB7DIGIymFRQABEEVIGg0ToynnszuQyCdAU4fCQjEIwFIoSgDviYBQwTANCNYkkMiZhLQyBQjGdUAAsiAo8oEbInWUoLH4zQ6naTEXysKnXUoABJIbEeAlssVhN1S1DcqlvtN0T64pQRRONC2LzFnPlbtV71gPTCgjsSrnCUNJrxaN6lD6vq6IA

**Comment by thiendangit** [comment]
ok! done
